da = input('Digite algo para saber suas info: ')
print('O seu tipo primitivo é', type(da))
print('Só tem espaços?', da.isspace())
print('É um número?', da.isnumeric())
print('É alfabético?', da.isalpha())
print('É alfanumérico', da.isalnum())
print('Esta em maiusculas?', da.isupper())
print('Esta em minuscula?', da.islower())
print('Está capitalizada?', da.istitle())